### ISSUE TITLE
add support for Linux and aarch64 Artifacts

### ISSUE THREAD

**Issue by rlinfati** [jump-dev/Gurobi_jll.jl#19]
[[Gurobi]]
git-tree-sha1 = " ¿? "
arch = "aarch64"
os = "linux"

    [[Gurobi.download]]
    sha256 = " ¿? "
    url = "https://anaconda.org/Gurobi/gurobi/11.0.2/download/linux-aarch64/gurobi-11.0.2-py311_0.tar.bz2"

**Comment by odow** [comment]
I'll make a PR, but I don't have a machine to test with so I might need your help :smile:

I'll comment with instructions shortly.

**Comment by odow** [comment]
I'll see if we can make a new release: https://github.com/jump-dev/Gurobi_jll.jl/pull/21

Otherwise you need `] add Gurobi_jll#master` until the next official release.

**Comment by odow** [comment]
A new version is released, so this should work if you update to the latest version.
