### ISSUE TITLE
Importing Gurobi_jll takes 1 minute

### ISSUE THREAD

**Issue by odow** [jump-dev/Gurobi_jll.jl#22]
See https://github.com/jump-dev/Gurobi.jl/pull/565#issuecomment-2175384783

Something isn't right. I've asked @sebastianangerhausen for more information.

**Comment by odow** [comment]
I'll debug in https://github.com/jump-dev/Gurobi_jll.jl/pull/23

**Comment by sebastianangerhausen** [comment]
```
julia> versioninfo()
Julia Version 1.10.1
Commit 7790d6f064 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_PKG_USE_CLI_GIT = true
  ```
  
It is a managed machine for work, so Julia was installed by our IT department. I could not observe anything special using the task manager.
