### ISSUE TITLE
Precompile Issue

### ISSUE THREAD

**Issue by ValentinKaisermayer** [jump-dev/Gurobi_jll.jl#24]
With Gurobi v1.3 im getting a precompile error, with v1.2.3 it works:
```
Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to "C:\\Users\\KaisermayerV\\.julia\\compiled\\v1.10\\Gurobi\\jl_4AA8.tmp".
ERROR: LoadError: InitError: IOError: chmod("C:\\Users\\KaisermayerV\\.julia\\packages\\DelaunayTriangulation\\04bDL\\test\\refinement\\refine_curve_bounded_example_11_multiply_connected_piecewise_linear_elliptical_bspline_piecewise_linear_catmull_bezier_piecewise_linear_circle_extra_points_1957263201006735060.png", 0o755): no such file or directory (ENOENT)
```

**Comment by odow** [comment]
Now that I look closer, I'm not sure why I have `dirname(dirname(artifact_dir))` in
https://github.com/jump-dev/Gurobi_jll.jl/blob/7808a850452a400f65aabb6b6ece177a6ce01da9/src/wrappers/x86_64-w64-mingw32.jl#L22

**Comment by odow** [comment]
If the tests pass on https://github.com/jump-dev/Gurobi_jll.jl/pull/25, can you try `] add Gurobi_jll#odow-patch-2`?

**Comment by odow** [comment]
Now I understand why https://github.com/jump-dev/Gurobi_jll.jl/issues/22 took 1 minute. We were changing the permission of _every_ file in `.julia`!!! Oops.

**Comment by odow** [comment]
I'm off to bed, but if you can confirm this is a fix, I'll sort a release tomorrow.
